<?php


namespace App\Form;


use App\Entity\City;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use OpenApi\Annotations as OA;

/**
 * @OA\RequestBody(
 *     request="CreateUpdateCity",
 *     required=true,
 *     @OA\JsonContent(
 *          required={"name", "county_code", "region"},
 *          @OA\Property(type="string", property="name"),
 *          @OA\Property(type="integer", property="county_code"),
 *          @OA\Property(type="string", property="region"),
 *          @OA\Property(type="string", property="mail_city"),
 *     )
 * )
 */
class CityForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("name", TextType::class)
            ->add("countyCode", NumberType::class)
            ->add("region", TextType::class)
            ->add("mailCity", EmailType::class)
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            "data_class" => City::class
        ]);
    }
}