<?php


namespace App\Form;

use App\Entity\Historic;
use App\Entity\Users;
use OpenApi\Annotations as OA;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @OA\RequestBody(
 *     request="CreateHistoric",
 *     required=true,
 *     @OA\JsonContent(
 *          required={"user_glassdump_uuid", "is_full", "is_damage"},
 *          @OA\Property(type="string", property="user_glassdump_uuid"),
 *          @OA\Property(type="boolean", property="is_full"),
 *          @OA\Property(type="boolean", property="is_damage"),
 *     )
 * )
 */
class HistoricForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("userGlassdumpUuid", EntityType::class, [
                "data_class" => Users::class
            ])
            ->add("isFull", )
            ->add("isDammage", )
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver
            ->setDefaults([
                "data_class" => Historic::class
                ]);
    }

}