<?php


namespace App\Form;


use App\Entity\Users;
use OpenApi\Annotations as OA;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @OA\RequestBody(
 *     request="Signin",
 *     required=true,
 *     @OA\JsonContent(
 *          required={"username", "password"},
 *          @OA\Property(type="string", property="username"),
 *          @OA\Property(type="string", property="password")
 *     )
 * )
 */
class SigninForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add("username", TextType::class)
            ->add("password", TextType::class)
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            'data_class' => Users::class
        ]);
    }

}